[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "genderAEye"
authors = [{name = "Devium", email = "devium335@gmail.com"}]
dynamic = ["version", "description"]